import fs from "fs/promises";
import { Octokit } from "@octokit/rest";

import { sanitizeRepoName } from "./repo-name";
import {
  listProjectFiles,
  removeTempDirectory,
  unzipArtifactToDirectory
} from "./unzip-artifact";

export type GitHubPushResult = {
  repoOwner: string;
  repoName: string;
  repoUrl: string;
  commitSha: string;
  branch: string;
  fileCount: number;
};

export { sanitizeRepoName };

async function ensureRepository(
  octokit: Octokit,
  owner: string,
  repoName: string,
  description: string
): Promise<string> {
  try {
    const { data } = await octokit.rest.repos.get({ owner, repo: repoName });
    return data.default_branch || "main";
  } catch (err: unknown) {
    const status = (err as { status?: number })?.status;
    if (status !== 404) {
      throw err;
    }
  }

  const { data } = await octokit.rest.repos.createForAuthenticatedUser({
    name: repoName,
    private: true,
    auto_init: true,
    description
  });
  return data.default_branch || "main";
}

async function getBranchHeadSha(
  octokit: Octokit,
  owner: string,
  repo: string,
  branch: string
): Promise<string | null> {
  try {
    const { data } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${branch}`
    });
    return data.object.sha;
  } catch {
    return null;
  }
}

export async function pushDirectoryToGitHub(input: {
  accessToken: string;
  owner: string;
  repoName: string;
  sourceDir: string;
  commitMessage: string;
  description?: string;
}): Promise<GitHubPushResult> {
  const octokit = new Octokit({ auth: input.accessToken });
  const repoName = sanitizeRepoName(input.repoName);
  const branch = await ensureRepository(
    octokit,
    input.owner,
    repoName,
    input.description ?? "Generated by App 生产工厂"
  );

  const files = await listProjectFiles(input.sourceDir);
  if (files.length === 0) {
    throw new Error("ZIP 解压后没有可推送的文件");
  }

  const treeItems: Array<{
    path: string;
    mode: "100644";
    type: "blob";
    sha: string;
  }> = [];

  for (const file of files) {
    const content = await fs.readFile(file.fullPath, "base64");
    const { data: blob } = await octokit.rest.git.createBlob({
      owner: input.owner,
      repo: repoName,
      content,
      encoding: "base64"
    });
    treeItems.push({
      path: file.relativePath,
      mode: "100644",
      type: "blob",
      sha: blob.sha
    });
  }

  const parentSha = await getBranchHeadSha(
    octokit,
    input.owner,
    repoName,
    branch
  );

  const { data: tree } = await octokit.rest.git.createTree({
    owner: input.owner,
    repo: repoName,
    tree: treeItems
  });

  const { data: commit } = await octokit.rest.git.createCommit({
    owner: input.owner,
    repo: repoName,
    message: input.commitMessage,
    tree: tree.sha,
    parents: parentSha ? [parentSha] : []
  });

  if (parentSha) {
    await octokit.rest.git.updateRef({
      owner: input.owner,
      repo: repoName,
      ref: `heads/${branch}`,
      sha: commit.sha
    });
  } else {
    await octokit.rest.git.createRef({
      owner: input.owner,
      repo: repoName,
      ref: `refs/heads/${branch}`,
      sha: commit.sha
    });
  }

  return {
    repoOwner: input.owner,
    repoName,
    repoUrl: `https://github.com/${input.owner}/${repoName}`,
    commitSha: commit.sha,
    branch,
    fileCount: files.length
  };
}

export async function pushArtifactZipToGitHub(input: {
  accessToken: string;
  owner: string;
  repoName: string;
  zipBuffer: Buffer;
  commitMessage: string;
  description?: string;
}): Promise<GitHubPushResult> {
  const sourceDir = await unzipArtifactToDirectory(input.zipBuffer, "push");
  try {
    return await pushDirectoryToGitHub({
      accessToken: input.accessToken,
      owner: input.owner,
      repoName: input.repoName,
      sourceDir,
      commitMessage: input.commitMessage,
      description: input.description
    });
  } finally {
    await removeTempDirectory(sourceDir);
  }
}
