import { readArtifactFile } from "@/lib/codegen/artifacts";
import { getCodegenRun, updateCodegenRun } from "@/lib/codegen/runs";
import { deriveCodegenRepoName } from "@/lib/github/repo-name";
import {
  pushArtifactZipToGitHub,
  type GitHubPushResult
} from "@/lib/github/push-artifact";
import { resolveGitHubPushCredentials } from "@/lib/github/push-token";

export type PushCodegenRunResult = {
  runId: string;
  target: string;
  push: GitHubPushResult;
  metadata: Record<string, unknown>;
};

export async function pushCodegenRunToGitHub(input: {
  userId: string;
  projectId: string;
  runId: string;
  repoName?: string;
}): Promise<PushCodegenRunResult> {
  const run = await getCodegenRun(input.runId);
  if (!run || run.project_id !== input.projectId) {
    throw new Error("codegen 记录不存在");
  }
  if (run.status !== "completed" || !run.artifact_path) {
    throw new Error("仅 completed 且有产物的 run 可推送 GitHub");
  }

  const credentials = await resolveGitHubPushCredentials(input.userId);
  if (!credentials) {
    const err = new Error("请先连接 GitHub 或配置 GITHUB_PAT");
    (err as Error & { code?: string }).code = "github_not_connected";
    throw err;
  }

  const meta = (run.metadata ?? {}) as {
    fileName?: string;
    displayName?: string;
  };

  const repoName =
    input.repoName?.trim() ||
    deriveCodegenRepoName({
      fileName: meta.fileName,
      displayName: meta.displayName,
      target: run.target,
      projectTitle: undefined
    });

  const zipBuffer = await readArtifactFile(run.artifact_path);
  const push = await pushArtifactZipToGitHub({
    accessToken: credentials.accessToken,
    owner: credentials.githubLogin,
    repoName,
    zipBuffer,
    commitMessage: `App Factory codegen push (${run.target})`,
    description: `Generated by App 生产工厂 · run ${run.id}`
  });

  const mergedMetadata = {
    ...(run.metadata ?? {}),
    githubPushStatus: "completed",
    githubRepoUrl: push.repoUrl,
    githubRepoOwner: push.repoOwner,
    githubRepoName: push.repoName,
    githubCommitSha: push.commitSha,
    githubBranch: push.branch,
    githubPushedAt: new Date().toISOString(),
    githubFileCount: push.fileCount
  };

  await updateCodegenRun(run.id, { metadata: mergedMetadata });

  return {
    runId: run.id,
    target: run.target,
    push,
    metadata: mergedMetadata
  };
}
