import { NextRequest, NextResponse } from "next/server";

import { getApiUser, unauthorizedResponse } from "@/lib/auth/api-user";
import { isAuthEnabled } from "@/lib/auth-config";
import { readArtifactFile } from "@/lib/codegen/artifacts";
import { getCodegenRun, updateCodegenRun } from "@/lib/codegen/runs";
import { guardProjectAccess } from "@/lib/auth/require-project-access";
import { getGitHubConnectionWithToken } from "@/lib/github/connections-server";
import { isGitHubOAuthEnabled } from "@/lib/github/config";
import { pushArtifactZipToGitHub } from "@/lib/github/push-artifact";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function deriveRepoName(input: {
  fileName?: string;
  displayName?: string;
  target: string;
  projectTitle?: string;
}): string {
  const fromFile = input.fileName?.replace(/\.zip$/i, "").replace(/-(flutter|wechat)$/i, "");
  const base = fromFile || input.displayName || input.projectTitle || "app-factory";
  const slug = base
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  const suffix = input.target === "wechat" ? "-wechat" : "-flutter";
  return `${slug || "app-factory"}${suffix}`;
}

export async function POST(
  req: NextRequest,
  { params }: { params: { id: string; runId: string } }
) {
  try {
    if (!isAuthEnabled()) {
      return NextResponse.json({ error: "Auth 未启用" }, { status: 503 });
    }
    if (!isGitHubOAuthEnabled()) {
      return NextResponse.json(
        { error: "GitHub OAuth 未配置" },
        { status: 503 }
      );
    }

    const user = await getApiUser();
    if (!user) {
      return unauthorizedResponse();
    }

    const denied = await guardProjectAccess(params.id);
    if (denied) {
      return denied;
    }

    const run = await getCodegenRun(params.runId);
    if (!run || run.project_id !== params.id) {
      return NextResponse.json({ error: "codegen 记录不存在" }, { status: 404 });
    }
    if (run.status !== "completed" || !run.artifact_path) {
      return NextResponse.json(
        { error: "仅 completed 且有产物的 run 可推送 GitHub" },
        { status: 400 }
      );
    }

    const connection = await getGitHubConnectionWithToken(user.id);
    if (!connection) {
      return NextResponse.json(
        { error: "请先连接 GitHub", code: "github_not_connected" },
        { status: 401 }
      );
    }

    const body = (await req.json().catch(() => ({}))) as {
      repoName?: unknown;
    };
    const meta = (run.metadata ?? {}) as {
      fileName?: string;
      displayName?: string;
    };

    const repoName =
      typeof body.repoName === "string" && body.repoName.trim()
        ? body.repoName.trim()
        : deriveRepoName({
            fileName: meta.fileName,
            displayName: meta.displayName,
            target: run.target,
            projectTitle: undefined
          });

    const zipBuffer = await readArtifactFile(run.artifact_path);
    const push = await pushArtifactZipToGitHub({
      accessToken: connection.accessToken,
      owner: connection.githubLogin!,
      repoName,
      zipBuffer,
      commitMessage: `App Factory codegen push (${run.target})`,
      description: `Generated by App 生产工厂 · run ${run.id}`
    });

    const mergedMetadata = {
      ...(run.metadata ?? {}),
      githubPushStatus: "completed",
      githubRepoUrl: push.repoUrl,
      githubRepoOwner: push.repoOwner,
      githubRepoName: push.repoName,
      githubCommitSha: push.commitSha,
      githubBranch: push.branch,
      githubPushedAt: new Date().toISOString(),
      githubFileCount: push.fileCount
    };

    await updateCodegenRun(run.id, { metadata: mergedMetadata });

    return NextResponse.json({
      ok: true,
      push,
      metadata: mergedMetadata
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "GitHub push 失败";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
